version: '3'
services:
  mongo_app:
    container_name: mongo_crud_app
    image: barbosajorge/mongo_crud_app
    build:
      context: $PWD
    restart: always
    ports: 
      - 8082:8082
    volumes:
      - $HOME/.m2:/root/.m2
      - $PWD:/tmp/mongo-app
    depends_on: 
      - mongodb
    environment:
      - MONGO_DB_HOST=mongodb
    networks:
      - net

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - $PWD/mongo_data:/data/db
    networks:
      - net

networks:
  net:

